
module.exports.jobs = [
    'Marketing Specialist',
    'Marketing Manager',
    'Marketing Director',
    'Graphic Designer',
    'Marketing Research Analyst',
    'Marketing Communications Manager',
    'Marketing Consultant',
    'Product Manager',
    'Public Relations',
    'Social Media Assistant',
    'Brand Manager',
    'SEO Manager',
    'Content Marketing Manager',
    'Copywriter',
    'Media Buyer',
    'Digital Marketing Manager',
    'eCommerce Marketing Specialist',
    'Brand Strategist',
    'Vice President of Marketing',
    'Media Relations Coordinator',
    'Administrative Assistant',
    'Receptionist',
    'Office Manager',
    'Auditing Clerk',
    'Bookkeeper',
    'Account Executive',
    'Branch Manager',
    'Business Manager',
    'Quality Control Coordinator',
    'Administrative Manager',
    'Chief Executive Officer',
    'Business Analyst',
    'Risk Manager',
    'Human Resources',
    'Office Assistant',
    'Secretary',
    'Office Clerk',
    'File Clerk',
    'Account Collector',
    'Administrative Specialist',
    'Executive Assistant',
    'Program Administrator',
    'Program Manager',
    'Administrative Analyst',
    'Data Entry',
    'Team Leader',
    'Manager',
    'Assistant Manager',
    'Executive',
    'Director',
    'Coordinator',
    'Administrator',
    'Controller',
    'Officer',
    'Organizer',
    'Supervisor',
    'Superintendent',
    'Head',
    'Overseer',
    'Chief',
    'Foreman',
    'Controller',
    'Principal',
    'President',
    'Lead',
    'Computer Scientist',
    'IT Professional',
    'UX Designer & UI Developer',
    'SQL Developer',
    'Web Designer',
    'Web Developer',
    'Help Desk Worker/Desktop Support',
    'Software Engineer',
    'Data Entry',
    'DevOps Engineer',
    'Computer Programmer',
    'Network Administrator',
    'Information Security Analyst',
    'Artificial Intelligence Engineer',
    'Cloud Architect',
    'IT Manager',
    'Technical Specialist',
    'Application Developer',
    'Chief Technology Officer (CTO)',
    'Chief Information Officer (CIO)',
    'Construction Worker',
    'Taper',
    'Plumber',
    'Heavy Equipment Operator',
    'Vehicle or Equipment Cleaner',
    'Carpenter',
    'Electrician',
    'Painter',
    'Welder',
    'Handyman',
    'Boilermaker',
    'Crane Operator',
    'Building Inspector',
    'Pipefitter',
    'Sheet Metal Worker',
    'Iron Worker',
    'Mason',
    'Roofer',
    'Solar Photovoltaic Installer',
    'Well Driller'
]